config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'users#dashboard'
  get 'edit-profile', to: 'users#edit'
  delete 'destroy-profile', to: 'users#destroy'
  get 'congrats', to: 'bookings#congrats'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  patch 'bookings/:id/decline', to: 'bookings#decline', as: 'decline_booking'


  devise_for :users
  resources :users, only: [:show, :update, :destroy]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews
  end

  mount Attachinary::Engine => "/attachinary"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attachment :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cats, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @reviews = []
    @user.bookings.each do |bk|
      unless bk.reviews.find { |rv| rv.user != @user }.nil?
        rev = bk.reviews.find { |rv| rv.user != @user }
        @reviews << rev
      end
    end
    if !current_user.nil?
      @user_past_booking = @user.bookings.find{ |e| (e.cat.user == current_user) && (e.ends_at < DateTime.now)}
      if @user_past_booking.nil?
        @user_review_needed = false
      else
        @user_review_needed = @user_past_booking.reviews.find{ |e| e.user_id == current_user.id }.nil?
      end
      @review = Review.new
    end
  end

  def edit
  end

  def update
    #comment
    current_user.update(user_params)
    redirect_to user_path(current_user)
  end

  def destroy
    current_user.destroy
    redirect_to root_path
  end

  def dashboard
    @cat = Booking.order(:updated_at).last.cat
    @reviews = []
    current_user.bookings.each do |bk|
      unless bk.reviews.find { |rv| rv.user != @user }.nil?
        rev = bk.reviews.find { |rv| rv.user != @user }
        @reviews << rev
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :description, :photo, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_rating.html.erb
<div class="cat-rating">
  <% count = reviews.count %>
  <% if count == 0 %>
    <small>no reviews yet</small>
  <% else %>
    <% mean = 0 %>
    <% reviews.each { |e| mean += (e.rating.to_i.fdiv(count)) } %>
    <% mean.round.times do %>
      <i class="fa fa-star" aria-hidden="true"></i>
    <% end %>
    <% if mean - mean.round > 0.5 %>
    <i class="fa fa-star-half" aria-hidden="true"></i>
    <% end %>
    <small><%= count %></small>
  <% end %>
</div>

app/views/users/dashboard.html.erb
  <div class="container container-dashboard container-spread">
    <div class="row">
      <div class="col-xs-12 col-md-9">
        <div class="dashboard-tabs">
          <div class="dashboard-tab active" id="mycats">
            <h2>My Cats</h2>
          </div>
          <div class="dashboard-tab" id="mybookings">
            <h2>My Bookings</h2>
          </div>
        </div>

        <div class="dashboard-tab-content" id="mycats-content">
          <% current_user.cats.each do |cat|%>
            <div class="dashboard-all-cat-informations">

              <div class="dashboard-cat-informations" id="<%= cat.id %>">
                <div class="dashboard-cat-photo">
                  <% if cat.photo? %>
                    <%= cl_image_tag cat.photo.path, transformation: [{width: 60, height: 60, gravity: 'face', radius: 'max', crop: 'fill'}], class: "cat-image" %>
                    <% else %>
                    <%= image_tag "cat-icon.png", width: 60, height: 60, crop: :fill, class: "cat-image" %>
                  <% end %>
                  <h1><%= cat.name %></h1>
                </div>
                <div class="dashboard-cat-rating">
                  <%= render 'cats/rating', cat: cat, count: 0, reviews: cat.reviews %>
                </div>
                  <% x = 0 %>
                  <% y = 0 %>
                  <% z = 0 %>
                  <% cat.bookings.each do |booking| %>
                    <% if booking.accepted == nil %>
                      <% x += 1 %>
                    <% elsif booking.accepted == true %>
                      <% y += 1 %>
                    <% else %>
                      <% z += 1 %>
                    <% end %>
                  <% end %>
                <div class="pending-bookings">
                  <p><%= x %> pending...</p>
                </div>
                <div class="pending-bookings">
                  <p><%= x + y + z %> booking(s)</p>
                </div>
              </div>
              <div class="row">
                <div class="dashboard-drop-down hidden" id="hidden-<%=cat.id%>">
                  <div class="col-xs-12 col-md-3">
                    <div class="dashboard-drop-down-left">
                      <div class="row">
                      <%= link_to cat_path(cat) do %>
                        <% if cat.photo? %>
                          <%= cl_image_tag cat.photo.path, width: 100, height: 100, crop: :fill, class: "cat-image cat-image-lien" %>
                        <% else %>
                          <%= image_tag "cat-icon.png", width: 100, height: 100, crop: :fill, class: "cat-image cat-image-lien" %>
                        <% end %>
                      <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-12 col-md-9">
                    <% cat.bookings.each do |booking| %>
                      <ul class="dashboard-booking-list list-inline">
                        <li>
                        <%= link_to user_path(booking.user) do %>
                          <% if booking.user.photo? %>
                          <%= cl_image_tag booking.user.photo.path, width: 50, height: 50, crop: :fill, class: "cat-image" %></li>
                          <% end %>
                        <% end %>

                          <li><p class="text-center"><%=booking.user.name%></p></li>
                          <li><p><%= render 'users/rating', user: booking.user, count: 0, reviews: @reviews %></p></li>
                        <li><p>from : <%= booking.start_at %></p>
                            <p>to : <%= booking.ends_at %></p>
                        </li>
                        <li><%= booking.price_per_day %><i class="fa fa-euro"></i></li>
                        <li>
                          <% if booking.start_at > Date.today %>
                            <% if booking.accepted == nil %>
                            <ul class="items-center">
                              <li class="accept-or-decline-list"> <%= link_to accept_booking_path(booking), method: :patch do  %>
                              <i class="fa fa-check"></i>
                            <% end %></li>
                              <li class="accept-or-decline-list"><%= link_to decline_booking_path(booking), method: :patch do  %>
                              <i class="fa fa-times"></i>
                            <% end %></li>
                            </ul>
                            <% elsif booking.accepted == true %>
                              <div class="accepted-button-dash fixe-button-widht text-center"><p>Accepted</p></div>
                            <% elsif booking.accepted == false %>
                              <div class="declined-button-dash fixe-button-widht text-center"><p>Declined</p></div>
                            <% end %>
                          <% elsif booking.ends_at < Date.today %>
                            <% if booking.reviews.find{|e| e.user == current_user} %>
                            <%= link_to user_path(booking.user) do %>
                              <button class="btn btn-primary fixe-button-widht">Add review</button>
                            <% end %>
                            <% else %>
                            <div class="allgood-button-dash fixe-button-widht text-center"><p>All Good</p></div>
                            <% end %>
                          <% end %>
                        </li>
                      </ul>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="dashboard-tab-content hidden" id="mybookings-content">
          <% current_user.bookings.each do |booking|%>
            <div class="dashboard-booking-informations">
                <div class="dashboard-cat-photo fixe-button-widht">
                  <%= link_to cat_path(booking.cat) do %>
                    <% if booking.cat.photo? %>
                      <%= cl_image_tag booking.cat.photo.path, transformation: [{width: 60, height: 60, gravity: 'face', radius: 'max', crop: 'fill'}], class: "cat-image" %>
                      <% else %>
                      <%= image_tag "cat-icon.png", width: 60, height: 60, crop: :fill, class: "cat-image" %>
                    <% end %>
                  <% end %>
                  <h1 class="fixe-button-widht"><%= booking.cat.name %></h1>
                </div>
                <div class="dashboard-cat-rating fixe-button-widht">
                  <%= render 'cats/rating', cat: booking.cat, count: 0, reviews: booking.cat.reviews %>
                </div>
                <div class="dashboard-cat-date">
                  <ul>
                    <li>from: <%= booking.start_at %></li>
                    <li>to: <%= booking.ends_at %></li>
                  </ul>
                </div>
                <div class="dashboard-bookings-price fixe-button-widht text-center">
                  <p><%= booking.price_per_day %><i class="fa fa-euro"></i></p>
                </div>
                <div>
                       <% if booking.accepted == nil %>
                        <div class="pending-button-dash fixe-button-widht text-center"><p>Pending...</p></div>
                      <% elsif booking.accepted == true %>
                        <div class="accepted-button-dash fixe-button-widht text-center"><p>Accepted</p></div>
                      <% elsif booking.accepted == false %>
                        <div class="declined-button-dash fixe-button-widht text-center"><p>Declined</p></div>
                    <% end %>

                </div>
                <div>
                  <% if booking.start_at > Date.today %>
                    <%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <div class="cancel-button-dash fixe-button-widht text-center"><p>Cancel</p></div>
                    <% end %>
                  <% elsif booking.ends_at < Date.today %>
                    <% if booking.reviews.find{|e| e.user == current_user} %>
                      <%= link_to cat_path(booking.cat) do %>
                        <div class="cancel-button-dash fixe-button-widht text-center"><p>Add review</p></div>
                      <% end %>
                    <% else %>
                      <% if booking.reviews.find{|e| e.user == current_user} %>
                        <%= link_to cat_path(booking.cat) do %>
                          <div class="allgood-button-dash fixe-button-widht text-center"><p>All Good</p></div>
                        <% end %>
                        <% else %>
                          <div class="allgood-button-dash fixe-button-widht text-center"><p>All Good</p></div>
                      <% end %>
                    <% end %>
                  <% else %>
                    <div class="cancel-button-dash fixe-button-widht text-center"><p>Enjoy</p></div>
                  <% end %>
              </div>
            </div>
            <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-3">
        <div class="right-card text-center">
          <div class="right-card-elem"->
            <% if current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, :transformation=>[
            {:width=>900, :height=>900, :gravity=>"face", :radius=>"max", :crop=>"crop"},
            {:width=>150, :crop=>"scale"}
            ] %>
          <% end %>
          </div>
          <div class="right-card-elem">
            <h3>  <%= current_user.name %></h3>
          <div class="right-card-elem"->
            <%= link_to  user_path(current_user), class: "text-center" do %>
              <p>  My profile</p>
            <% end %>
          </div>
          <div class="right-card-elem"->
            <%= link_to new_cat_path class: "text-center" do %>
              <p> New cat </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function() {
    var cat_id = <%= @cat.id %>;
    $("#hidden-"+cat_id).toggleClass('hidden');
  });
</script>
<% end %>

app/views/users/edit.html.erb
<div class="text-center container-with-footer">
  <h1 class="no-top-margin">Edit your profile</h1>

  <div class="form-inputs">
    <%= simple_form_for (current_user) do |f| %>
      <%= f.error_notification %>

      <%= f.input :name, required: true%>
      <%= f.input :description, required: true%>
      <%= f.input :photo, as: :attachinary %>

      <%= f.submit "Update profile", class: "btn btn-primary" %>
    <% end %>
  </div>
    <%= link_to "Update account settings", edit_user_registration_path %>

</div>

app/views/users/show.html.erb
<div class="wrapper text-center container-spread">

  <% if user_signed_in? && current_user.id == @user.id%>
    <h1 class="no-top-margin">My profile</h1>
  <%else%>
    <h1 class="no-top-margin">Meet <%=@user.name%></h1>
  <%end%>

<div class="container">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-4">
      <div class="profile-box-left">
        <div class="big-avatar">
            <% if @user.photo? %>
              <%= cl_image_tag @user.photo.path, :transformation=>[
            {:width=>300, :height=>300, :gravity=>"face", :radius=>"max", crop: :fill},
            {width: 150, crop: :fill}
            ] %>

            <% end %>
          </div>
          <div class="confirmation-info">
            <p>Name : <strong><%=@user.name%></strong></p>
          </div>
            <br>
          <div class="confirmation-info">
            <p>Email address :</p>
            <p><strong><%=@user.email%></strong></p>
          </div>
            <br>
          <div class="confirmation-info">
            <p>Description :</p>
            <p><strong><%=@user.description%></strong></p>
          </div>
          <% if user_signed_in? && current_user.id == @user.id%>
    <div class="btn-edit">
      <%= link_to "Edit Profile", edit_profile_path, class: "btn btn-primary btn-space" %>
      <%= link_to "Delete Profile", user_path(@user), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
      </div>
    </div>
    <div class="col-xs-4 col-xs-offset-2">
      <h2>Reviews</h2>

      <div id="reviews">
        <% @reviews.each do |rev|%>
        <div class="row">
          <div class="col-xs-3">
            <% if rev.user.photo? %>
              <%= cl_image_tag rev.user.photo.path, class: "avatar-large"%>
            <% else %>
              <img class="avatar-large" src="http://lorempixel.com/200/200/people/<%=@cat.id%>">
            <% end %>
            <h4><%= rev.user.name%></h4>
          </div>
          <div class="col-xs-9">
            <div class="cat-rating">
              <% rev.rating.round.times do %>
                <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
            </div>
            <p><%= rev.content%></p>
            <hr>
          </div>
        </div>
        <% end %>
      <div class="line"></div>
      <div class="profile-form-review">
        <% if @user_review_needed %>
        <%= render 'reviews/form', booking: @user_past_booking, review: @review%>
        <% end %>
      </div>
    </div>
  </div>
</div>


</div>