config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'users#dashboard'
  get 'edit-profile', to: 'users#edit'
  delete 'destroy-profile', to: 'users#destroy'
  get 'congrats', to: 'bookings#congrats'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  patch 'bookings/:id/decline', to: 'bookings#decline', as: 'decline_booking'


  devise_for :users
  resources :users, only: [:show, :update, :destroy]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:show, :destroy] do
    resources :reviews
  end

  mount Attachinary::Engine => "/attachinary"


end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  validates :name, presence: true
  validates :race, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true

  has_attachment :photo

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :get_current_user, only: [:create, :update]

  def index
    session[:booking_start_at] = params[:start_at] if params[:start_at].present?
    session[:booking_end_at] = params[:end_at] if params[:end_at].present?
    session[:address] = params[:address] if params[:address].present?
    @cats = Cat.near(params[:address] || 'Paris')
    @cats = @cats.where("start_at <= ?", params[:start_at].to_date) if params[:start_at].present?
    @cats = @cats.where("end_at >= ?", params[:end_at].to_date) if params[:end_at].present?
    @hash = Gmaps4rails.build_markers(@cats) do |cat, marker|
      marker.lat cat.latitude
      marker.lng cat.longitude
      marker.infowindow render_to_string(partial: "/cats/map_box", locals: { cat: cat })
    end
  end

  def show
    @cat = Cat.find(params[:id])
    @booking = Booking.new
    @cat_coordinates = { lat: @cat.latitude, lng: @cat.longitude }
    @reviews = []
      @cat.bookings.each do |bk|
        unless bk.reviews.find{ |rv| rv.user != @cat.user }.nil?
          rev = bk.reviews.find{ |rv| rv.user != @cat.user }
          @reviews << rev
        end
      end
    if !current_user.nil?
      @current_user_past_booking = current_user.bookings.find{ |e| (e.cat == @cat) && (e.ends_at < DateTime.now)}
        if !@current_user_past_booking.nil?
          @current_user_review_needed = @current_user_past_booking.reviews.find{ |e| e.user_id == current_user.id }.nil?
        else
          @current_user_review_needed = false
        end
      @review = Review.new
    end
  end

  def create
    @cat = Cat.new(user_params)
    @cat.user = @user
    @cat.save
    redirect_to cats_path
  end

  def new
    @cat = Cat.new
  end

  def edit

  end

  def update
    @cat.update(user_params)
    redirect_to cat_path(@cat)
  end

  def destroy
    @cat.destroy
    redirect_to cats_path
  end

  private

  def user_params
    params.require(:cat).permit(:name, :race, :age, :address, :price_per_day, :description, :cage, :litter, :cat_tree, :toys, :bowl, :outdoor, :belly_rubs, :start_at, :end_at, :photo)
  end

  def set_cat
    @cat = Cat.find(params[:id])
  end

  def get_current_user
    @user = current_user
  end
end

app/helpers/cats_helper.rb
module CatsHelper
  def cat_photo_path(photo)
    if photo
      cl_image_path photo.path, height: 300, width: 400, crop: :fill
    else
      "http://res.cloudinary.com/das218bbz/image/upload/v1489587060/default-cat-picture_kqygl0.jpg"
    end
  end

  def cat_user_photo_path(photo)
    if photo
      cl_image_path photo.path, height: 300, width: 400, crop: :fill
    else
      "http://res.cloudinary.com/das218bbz/image/upload/v1489587059/logo_g0vbcr.png"
    end
  end
end

app/views/cats/_card.html.erb
<div class="col-xs-12 col-sm-6">
  <div class="card-index">
    <div class="card-index-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cat_photo_path(cat.photo) %>');">

     <a class="card-link" href=<%=cat_path(cat)%> ></a>
     <%= cl_image_tag cat_user_photo_path(cat.user.photo), transformation: [{width: 75, height: 75, gravity: 'face', radius: 'max', crop: :fill}], class: "avatar card-user" %>
    </div>
    <div class="card-index-text">
      <div class="card-index-text-row">
        <div class="card-index-text-price">
          <strong><%=cat.price_per_day%> €</strong>
        </div>
        <%= render 'rating', cat: cat, count: 0, reviews: reviews%>
      </div>
      <div class="card-index-text-row">
        <h5><%=cat.name%> - <%=cat.race%></h5>
      </div>
      <div class="card-index-text-row">
        <small><%=cat.age%> ans · <%=cat.address%></small>
      </div>
    </div>
  </div>
</div>

app/views/cats/_form.html.erb
<%= simple_form_for @cat do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.label :name, "Name:"%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :race, "Race:"%>
    <%= f.text_field :race, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :age, "Age:"%>
    <%= f.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, "Address:"%>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :drescription, "Description:"%>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price_per_day, "Price per day:"%>
    <%= f.text_field :price_per_day, class: "form-control" %>
  </div>
  <div class="form-group input-daterange">
    <%= f.input :start_at, label: "Starts at:", class: "form-control actual_range" %>
    <%= f.input :end_at, label: "Ends at:", class: "form-control actual_range" %>
  </div>
  <div class="form-group">
  <%= f.input :photo, as: :attachinary %>
  </div>
  <div class="form-group">
  <%= f.submit "Create Cat", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/cats/_map_box.html.erb
<div class="owner-card">
            <% if cat.user.photo? %>
              <img class="avatar" src=<%= image_path cat.user.photo%> >
            <% else %>
              <img class="avatar" src="http://lorempixel.com/200/200/people/">
            <% end %>
            <h3><%= cat.name%></h3>
            <h4><strong><%= cat.price_per_day%> € par jour !</strong></h4>
            <p><%= cat.address%></p>
</div>

app/views/cats/_rating.html.erb
<div class="cat-rating">
  <% if reviews.count == 0 %>
    <small>no reviews yet</small>
  <% else %>
    <% mean = 0 %>
    <% count = reviews.count %>
    <% reviews.each { |e| mean += (e.rating.to_i.fdiv(count)) } %>
    <% mean.round.times do %>
      <i class="fa fa-star" aria-hidden="true"></i>
    <% end %>
    <% if mean - mean.round > 0.5 %>
    <i class="fa fa-star-half" aria-hidden="true"></i>
    <% end %>
    <small><%= count %></small>
  <% end %>
</div>

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/destroy.html.erb
<h1>Cats#delete</h1>
<p>Find me in app/views/cats/delete.html.erb</p>

app/views/cats/edit.html.erb
<div class="container container-with-footer">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cats/index.html.erb
<div class="container-without-footer">
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-7">
      <div class="wider-container card-container">
        <div class="row">
          <% @cats.each do |cat| %>
            <%reviews = []%>
            <%cat.bookings.each do |bk|%>
              <%unless bk.reviews.find{ |rv| rv.user != cat.user }.nil?%>
                <%rev = bk.reviews.find{ |rv| rv.user != cat.user }%>
                <%reviews << rev%>
              <%end%>
          <%end%>
          <%= render 'card', cat: cat, reviews: reviews %>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-5 nopadding">
      <div id="map" class="wider-container">
        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).ready(function() {
              var handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function() {
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                if (markers.length == 0) {
                  handler.getMap().setZoom(2);
                } else if (markers.length == 1) {
                  handler.getMap().setZoom(14);
                }
              });
            });
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/cats/new.html.erb
<div class="container container-with-footer">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cats/show.html.erb
<% if @cat.photo? %>

<div class="banner banner-show" style="background-image: url(<%= cl_image_path @cat.photo.path %>);">


<% else %>
<div class="banner banner-show" style="background-image: url(<%="http://lorempixel.com/1200/600/cats/#{@cat.id}"%>);">
<%end%>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="row row-cat-char">
        <div class="col-xs-2 col-owner-card">
          <div class="owner-card text-center">
            <% if @cat.user.photo? %>
              <%= link_to user_path(@cat.user_id) do %>
                <%= cl_image_tag @cat.user.photo.path, class: "avatar-large"%>
              <%end%>
            <% else %>
              <%= link_to user_path(@cat.user_id) do %>
                <img class="avatar-large" src="http://lorempixel.com/200/200/people/<%=@cat.id%>">
              <%end%>
            <% end %>
            <p><%= @cat.user.name%></p>
          </div>
        </div>
        <div class="col-xs-10 col-cat-name-adress-char">
          <div class="col-xs-12 cat-pres">
            <div class="col-xs-6">
              <h1><%= @cat.name %></h1>
            </div>
            <div class="col-xs-6 cat-address">
              <small><%= @cat.address %></small>
            </div>
          </div>
          <div class="col-xs-12">
            <div class="row text-center cat-characteristics">
              <div class="col-xs-3">
                <div class="icon-and-race">
                  <%= image_tag 'cat-icon.png', class: "cat-icon" %>
                  <p><span class="show-race"><%= @cat.race %></span></p>
                </div>
              </div>
              <div class="col-xs-3">
                <div class="cat-age">
                  <% if @cat.age.to_f < 1 %>
                    <h3>A few</h3>
                    <p>monthes old</p>
                  <%else%>
                    <h3><%= @cat.age %></h3>
                    <p>years old</p>
                  <%end%>
                </div>
              </div>
              <div class="col-xs-3">
                <%= render 'rating', cat: @cat, count: 0, reviews: @reviews %>
              </div>
              <div class="col-xs-3">
                <div class="cat-age">
                  <h3><%=@cat.price_per_day%><span style="font-size:20px;">€</span></h3>
                  <p>per day</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-2">
          <div class="cat-description">
            <i class="fa fa-quote-left" aria-hidden="true"></i><p><%= @cat.description %></p><i class="fa fa-quote-right" aria-hidden="true"></i>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-2">
          <div class="reviews-div">
            <h4>
              <%= pluralize @reviews.size, "review" %>!
              </h4>
            <% @reviews.each do |rev|%>
            <div class="row">
              <div class="col-xs-3 text-center">
                <% if rev.user.photo? %>
                  <%= link_to user_path rev.user do %>
                    <%= cl_image_tag rev.user.photo.path, class: "avatar-large"%>
                  <% end %>
                <% else %>
                  <img class="avatar-large" src="http://lorempixel.com/200/200/people/<%=@cat.id%>">
                <% end %>
                <h5><%= rev.user.name%></h5>
              </div>
              <div class="col-xs-9">
                <div class="cat-rating">
                <% rev.rating.round.times do %>
                  <i class="fa fa-star" aria-hidden="true"></i>
                <% end %>
                </div>
                <p><%= rev.content%></p>
                <hr>
              </div>
            </div>
            <% end%>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-2">
          <div class="owner-card">
            <h4>My owner</h4>
            <hr>
            <div class="row">
              <div class="col-xs-2">
                <% if @cat.user.photo? %>
                  <%= link_to user_path(@cat.user_id) do %>
                    <%= cl_image_tag @cat.user.photo.path, class: "avatar-large"%>
                  <%end%>
                <% else %>
                <%= link_to user_path(@cat.user_id) do %>
                  <img class="avatar-large" src="http://lorempixel.com/200/200/people/<%=@cat.id%>">
                <%end%>
                <% end %>
                <h5><%= @cat.user.name%></h5>
              </div>
              <p><%= @cat.user.description%></p>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-xs-1">
          <%= link_to "Back to index", cats_path, class: "btn btn-primary" %>
        </div>
        <% if current_user == @cat.user %>
          <div class="col-xs-1 col-xs-offset-7">
            <%= link_to "Edit #{@cat.name}", edit_cat_path(@cat), class: "btn btn-warning" %>
          </div>
          <div class="col-xs-1 col-xs-offset-1">
            <%= link_to "Delete #{@cat.name}", cat_path(@cat),
            method: :delete,
            class: "btn btn-warning" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-3">
      <div class="booking-title">
        <% if @current_user_review_needed %>
          <h4>Review <%= @cat.name%>!</h4>
        <% else %>
          <h4>Book <%= @cat.name%>!</h4>
        <% end %>
      </div>
      <div class="booking">
        <% if current_user.nil? %>
          <p>Please <%= link_to 'sign up', '/users/sign_up', class: "btn btn-primary" %> to book a cat!</p>
        <% else %>
            <% if @current_user_review_needed %>
              <div class="cat-show-review-form">
                <%= render 'reviews/form', booking: @current_user_past_booking, review: @review%>
              </div>
            <% else %>
              <%= form_tag(new_cat_booking_path(@cat), method: :get, class: "booking_form text-center") %>

            <div class="input-group input-daterange" id="booking_period" >
              <%= text_field_tag :start_at, nil, placeholder: 'Start date', value: session[:booking_start_at], class: "form-control actual_range" %>
              <br>
              <%= text_field_tag :ends_at, nil, placeholder: "End date", value: session[:booking_end_at], class: "form-control actual_range"%>
            </div>
              <%= hidden_field_tag :user_id, current_user.id %>
              <%= hidden_field_tag :cat_id, @cat.id %>
              <%= hidden_field_tag :price_per_day, @cat.price_per_day %>
              <%= submit_tag "Book #{@cat.name}", class: "btn btn-primary" %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>